  development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: japantravel_dev
  pool: 5
  username: japantravel
  password: test1234
test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: japantravel_test
  pool: 5
  username: japantravel
  password: test1234
production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: japantravel_pr
  pool: 5
  username: japantravel
  password: test1234
