default: &default
  aws:
    access_key_id: 'AKIAIXGULPWFCW53SUFA'
    secret_access_key: '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'
  s3:
    bucket: 'japantravel-development2'
    hostname: 's3-website-ap-northeast-1.amazonaws.com'

development:
  <<: *default
  s3:
    bucket: 'japantravel'
    hostname: 's3-website-ap-northeast-1.amazonaws.com'

test:
  <<: *default
  s3:
    bucket: 'japantravel-development2'
    hostname: 's3-website-ap-northeast-1.amazonaws.com'


production:
  <<: *default
  s3:
    bucket: 'apantravel-development2'
    hostname: 's3-website-ap-northeast-1.amazonaws.com'
